title: Awesome Lists
description: Curated Awesome Lists across AI, programming, security, sustainability, and emerging technologies.
baseurl: ""
url: "https://awesomelists.io"
timezone: America/Toronto

markdown: kramdown
permalink: /:title/

collections:
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

twitter:
  username: ListsAwesome
  card: summary_large_image

logo: /logo.svg