title: Awesome Lists
description: Curated Awesome Lists across AI, programming, security, sustainability, and emerging technologies.
baseurl: ""
url: "https://awesomelistsio.github.io/www"

markdown: kramdown
permalink: /blog/:title/

collections:
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
